
import Scroll from "@/components/Scroll/Scroll";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";



export const metadata = {
  title: "Md Shamiul Islam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="bg-gradient-to-br from-gray-800 to-black text-white  scroll-smooth overflow-x-hidden-hidden "
      >

        <Navbar />
        <main>
          {children}
          <Scroll/>
        </main>

      </body>
    </html>
  );
}
